/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model.tables;


import com.example.jooq.model.Keys;
import com.example.jooq.model.Public;
import com.example.jooq.model.tables.records.UserfactoryRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userfactory extends TableImpl<UserfactoryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.userfactory</code>
     */
    public static final Userfactory USERFACTORY = new Userfactory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserfactoryRecord> getRecordType() {
        return UserfactoryRecord.class;
    }

    /**
     * The column <code>public.userfactory.id</code>.
     */
    public final TableField<UserfactoryRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.userfactory.merchantid</code>.
     */
    public final TableField<UserfactoryRecord, String> MERCHANTID = createField(DSL.name("merchantid"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.userfactory.apikey</code>.
     */
    public final TableField<UserfactoryRecord, String> APIKEY = createField(DSL.name("apikey"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.userfactory.urlback</code>.
     */
    public final TableField<UserfactoryRecord, String> URLBACK = createField(DSL.name("urlback"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.userfactory.requestmethod</code>.
     */
    public final TableField<UserfactoryRecord, String> REQUESTMETHOD = createField(DSL.name("requestmethod"), SQLDataType.CLOB.nullable(false), this, "");

    private Userfactory(Name alias, Table<UserfactoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private Userfactory(Name alias, Table<UserfactoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.userfactory</code> table reference
     */
    public Userfactory(String alias) {
        this(DSL.name(alias), USERFACTORY);
    }

    /**
     * Create an aliased <code>public.userfactory</code> table reference
     */
    public Userfactory(Name alias) {
        this(alias, USERFACTORY);
    }

    /**
     * Create a <code>public.userfactory</code> table reference
     */
    public Userfactory() {
        this(DSL.name("userfactory"), null);
    }

    public <O extends Record> Userfactory(Table<O> child, ForeignKey<O, UserfactoryRecord> key) {
        super(child, key, USERFACTORY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UserfactoryRecord, Integer> getIdentity() {
        return (Identity<UserfactoryRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserfactoryRecord> getPrimaryKey() {
        return Keys.USERFACTORY_PKEY;
    }

    @Override
    public Userfactory as(String alias) {
        return new Userfactory(DSL.name(alias), this);
    }

    @Override
    public Userfactory as(Name alias) {
        return new Userfactory(alias, this);
    }

    @Override
    public Userfactory as(Table<?> alias) {
        return new Userfactory(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Userfactory rename(String name) {
        return new Userfactory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Userfactory rename(Name name) {
        return new Userfactory(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Userfactory rename(Table<?> name) {
        return new Userfactory(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Integer, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Integer, ? super String, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
