/*
 * This file is generated by jOOQ.
 */
package com.example.jooq.model;


import com.example.jooq.model.tables.Conclusions;
import com.example.jooq.model.tables.FlywaySchemaHistory;
import com.example.jooq.model.tables.Payments;
import com.example.jooq.model.tables.Userfactory;
import com.example.jooq.model.tables.Users;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.conclusions</code>.
     */
    public final Conclusions CONCLUSIONS = Conclusions.CONCLUSIONS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.payments</code>.
     */
    public final Payments PAYMENTS = Payments.PAYMENTS;

    /**
     * The table <code>public.userfactory</code>.
     */
    public final Userfactory USERFACTORY = Userfactory.USERFACTORY;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.HIBERNATE_SEQUENCE
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Conclusions.CONCLUSIONS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Payments.PAYMENTS,
            Userfactory.USERFACTORY,
            Users.USERS
        );
    }
}
