CREATE TABLE IF NOT EXISTS Users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) not null,
    password varchar(255) not null,
    tron_balance double precision NOT NULL,
    bitcoin_balance double precision NOT NULL,
    ethereum_balance double precision NOT NULL,
    matic_balance double precision NOT NULL,
    registeredAt varchar(255) not null
);
