CREATE TABLE IF NOT EXISTS Users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(15) not null,
    password varchar(255) not null,
    registeredAt varchar(255) not null
);
